<?php

namespace Pyz\Yves\Computop\Mapper;

use Generated\Shared\Transfer\ComputopPayPalExpressPaymentTransfer;
use Generated\Shared\Transfer\QuoteTransfer;
use Spryker\Yves\Router\Router\Router;
use SprykerEco\Shared\Computop\Config\ComputopApiConfig;
use SprykerEco\Yves\Computop\Mapper\Init\PostPlace\PayPalExpressMapper as EcoPayPalExpressMapperAlias;
use SprykerEco\Yves\Computop\Plugin\Router\ComputopRouteProviderPlugin;

class PayPalExpressMapper extends EcoPayPalExpressMapperAlias
{
    /**
     * @param QuoteTransfer $quoteTransfer
     *
     * @return ComputopPayPalExpressPaymentTransfer
     */
    public function createComputopPaymentTransfer(QuoteTransfer $quoteTransfer): ComputopPayPalExpressPaymentTransfer
    {
        $computopPaymentTransfer = parent::createComputopPaymentTransfer($quoteTransfer); // TODO: Change the autogenerated stub

        $computopPaymentTransfer->setUrlFailure(
            $this->router->generate(ComputopRouteProviderPlugin::ROUTE_NAME_PAY_PAL_EXPRESS_PLACE_ORDER, [], Router::ABSOLUTE_URL),
        );

        $decryptedValues = $this->computopApiService->getEncryptedArray(
            $this->getDataSubArray($computopPaymentTransfer),
            $this->config->getBlowfishPassword(),
        );

        $computopPaymentTransfer->setData($decryptedValues[ComputopApiConfig::DATA]);
        $computopPaymentTransfer->setLen($decryptedValues[ComputopApiConfig::LENGTH]);

        return $computopPaymentTransfer;
    }
}
